# fly.toml app configuration file generated for rpg-de-mesa-vusalq on 2026-10-03T21:34:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rpg-de-mesa-vusalq'
primary_region = 'gru'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
